global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
  web-secure:
    address: :443

log:
  level: DEBUG
  format: json

api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: krane
    watch: true

certificatesResolvers:
  lets-encrypt:
    acme:
      email: "LETSENCRYPT_EMAIL"
      storage: acme.json
      tlsChallenge: {}
      httpChallenge:
        entryPoint: web
