global:
  checkNewVersion: true
  sendAnonymousUsage: false

defaultEntryPoints:
  - https
  - http

entryPoints:
  web:
    address: :80
  web-secure:
    address: :443

log:
  level: DEBUG
  format: json
  filePath: /etc/traefik/traefik.log

api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: true
    network: krane
    watch: true

certificatesResolvers:
  lets-encrypt:
    acme:
      email: "biensupernice@gmail.com"
      storage: "/acme.json"
      tlsChallenge: true
