global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :80
  https:
    address: :443

log:
  level: DEBUG
  format: json
  filePath: /etc/traefik/traefik.log

api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: true
    network: krane

certificatesResolvers:
  krane:
    acme:
      email: "traefik@krane.sh"
      storage: "acme.json"
      httpChallenge:
        entryPoint: http
